### ISSUE TITLE
Website says “Offsets are missing for iPhone 5s”

### ISSUE THREAD

**Issue by thename2468** [userlandkernel/jailbreakme-unified#2]
Sorry if this isn’t useful. I’m a GitHub noob.

**Comment by thename2468** [comment]
Im also on iOS 12.01 btw

**Comment by mygizli04** [comment]
I mean there is the answer right there on the title. “Offsets are missing for iPhone 5s”. Not really an issue, just not implemented yet. Also just in case you think you can install Cydia with this, you can’t.

**Comment by userlandkernel** [comment]
Thanks for the correct explanation @mygizli04, offsets need to be added accordingly.
Feel free to add a pull request, you can retrieve them with the UFOFinder I wrote.
It might be hard if you don't understand what this all about, in that case I suggest you wait until the exploit is completed and take a beer in the meantime, just not too many beers because it might take a while.
